### ISSUE TITLE
Crash on the server side (Minecraft 1.8.9)

### ISSUE THREAD

**Issue by Leeo97one** [Sinhika/SimpleCore#1]
[crash-2016-03-27_17.21.15-server.txt](https://github.com/Sinhika/SimpleCore/files/190974/crash-2016-03-27_17.21.15-server.txt)

**Comment by Sinhika** [comment]
Should be fixed by latest release ( v1.2.3.1)

**Comment by Leeo97one** [comment]
It works, thank you!
