### ISSUE TITLE
Arrow count fluctuates up-and-down when firing from a Simple Ores bow

### ISSUE THREAD

**Issue by fandomaniac** [Sinhika/SimpleCore#12]
The arrow count fluctuates when firing from a Simple Ores bow. 
For example, I'm firing from a Mythril Bow, the arrow count jumps up-and-down. I start with 50, fire one, and now 49, fire another and now I have 51. I fire again and now I have 54 arrows.

Mod Version: simplecore-1.12.2-1.7.3.0.jar
Forge Version: 1.12.2 - 14.23.5.2772

**Comment by Sinhika** [comment]
I investigated this. This is a client-server update rate issue, and only applies to the Mythril bow. The Mythril bow has the "Efficiency" feature, which acts like a budget Infinity enchantment and sometimes does NOT use up the arrow (i.e., this is an intended feature). If you rapid-fire your bow, your client is a bit late about updating the count of arrows still in your inventory.  You may notice that if you slow-fire, pausing between each shot with a Mythril bow, the arrow count either stays the same or goes down; it does not jump back up. I'm not sure if this is something I can fix, or if it is a fundamental Minecraft issue.

**Comment by fandomaniac** [comment]
I just ran some more tests. I've tested Mythril, Onyx, vanilla, Bloodwood and other bows from Natura. The issue only seems to be with both Mythril and Onyx bows. Mythril and Onyx bows are the only ones that seem to be fluctuating the count (both up and down), when firing rapidly. The other bows deplete one with every fire, even at fast speeds. I have also tested on single-player and SMP, with the same results. It's not a big deal, but wanted you to be aware that the issue seems to only be with SimpleOre bows. Besides that, SimpleOres continues to be one of my favorite mods and is consistently added to every modpack I've created. Thank you  for all your hard work keeping this awesome mod alive!

**Comment by Sinhika** [comment]
Have you tested it with Sinisite and Thyrium Bows (from Fusion)?  I have been unable to duplicate this effect except with the Mythril bow, and then only partially.  It could be a mod interaction, too. What mods are you using along with Simple Ores?

**Comment by fandomaniac** [comment]
I don't have Fusion installed. Besides SimpleOres, the only mods I'm using that have additional bow types are Natura and Tinkers Construct.

Here's a list of all the mods in my pack (running Forge 1.12.2-14.23.5.2769):
AutoRegLib-1.3-20.jar
BetterFps-1.4.8.jar
BiblioCraft[v2.4.5][MC1.12.2].jar	
ChestTransporter-1.12.2-2.8.8.jar	
Craftable+Saddles[1.12]-1.3.jar
Chameleon-1.12-4.1.3.jar
CookingForBlockheads_1.12.2-6.4.65.jar	
CustomNPCs_1.12.2(26aug18).jar
CreativeCore_v1.9.35_mc1.12.2.jar
Decocraft-2.6.2_1.12.2.jar
DungeonTactics-1.12.2-0.15.6.jar
DynamicLights-1.12.2.jar	
Electroblob's Wizardry - 4.1.2 - MC 1.12.2.jar	
Dungeons2-mc1.12-f14.21.1.2387-v1.3.3.jar	
BetterFps-1.4.8.jar	
FastLeafDecay-v14.jar
GottschCore-mc1.12.2-f14.23.4.2705-v1.5.0.jar
Hwyla-1.8.26-B41_1.12.2.jar
InfernalMobs-1.12.2.jar
InGameInfoXML-1.12.2-2.8.2.94-universal.jar
JRFTL[1.12.2]-1.1.jar	
LibEx-1.12.2-1.0.8.jar	
LootBags-1.12.2-2.5.7.jar
LunatriusCore-1.12.2-1.2.0.42-universal.jar	
LycanitesMobsComplete 1.20.4.2 [1.12.2].jar	
Mantle-1.12-1.3.2.24.jar
NoMoreRecipeConflict-0.12(1.12.2).jar	
NetherEx-1.12.2-2.0.8.jar
OnlinePicFrame_v1.4.21_mc1.12.2.jar	
OpenBlocks-1.12.2-1.8.jar	
OpenModsLib-1.12.2-0.12.1.jar	
PTRLib-1.0.3.jar	
Pam's HarvestCraft 1.12.2za.jar	
Quark-r1.5-130.jar
QuarkOddities-1.12.2.jar	
RoguelikeDungeons-1.12.2-1.8.0.jar	
SimplyEnchanting-1.12-1.0.3.jar	
StorageDrawers-1.12.2-5.3.7.jar	
TConstruct-1.12.2-2.10.1.87.jar	
TreeChopper-1.12.2-1.2.4.jar	
VariedCommodities_1.12.2(15may18.jar
WailaHarvestability-mc1.12-1.1.12.jar	
Waystones_1.12.2-4.0.67.jar	
backpacks 1.12.2 - 3.5.4.jar	
cjcm-1.0.jar	
corail_pillar-4.1.0-1.12.jar	
corail_pillar_extension_quark-4.0.0-1.12.jar	
device-mod-0.4.1-1.12.2.jar	
foamfix-0.10.2-1.12.2.jar	
foamflower-1.12.2-1.0.0.0-beta1.jar	
furniture-5.15.0-1.12.2.jar	
gravestone-1.10.1.jar	
ironchest-1.12.2-7.0.40.824.jar	
jei_1.12.2-4.13.1.220.jar	
malisisblocks-1.12.2-6.1.0.jar	152.9 kB	2018-02-15 22:57	
malisiscore-1.12.2-6.4.0.jar	1.8 MB	2018-02-15 22:57	
malisisdoors-1.12.2-7.3.0.jar	
natura-1.12.2-4.3.2.62.jar
obfuscate-0.2.6-1.12.2.jar
paintingselgui-PSG+Revamed-1.12.2-1.1.0.1.jar	
simplecore-1.12.2-1.7.3.4.jar	
simpleores-1.12.2-1.11.2.2.jar	
soccer-mod-1.0-1.12.2.jar	
varodd-1.12.2-4.0.jar
vehicle-mod-0.21.0-1.12.2.jar	
vending-1.12.2-3.0.1.2.jar	
worldutils-1.12.2-0.4.2.jar
