### ISSUE TITLE
[1.18.2][4.3.1.3] Broken bow pulling animation

### ISSUE THREAD

**Issue by Thombias** [Sinhika/SimpleCore#14]
Hey there, while playing around with Zot's Only Silver i noticed that the bow pulling animations for all bows is no longer playing on the most recent versions: 

![Simple Mods Broken Bow Animation](https://user-images.githubusercontent.com/46842890/169518308-e0601ed5-d816-402d-b923-0bf325a792c6.gif)

Tested with the following mod versions:

SimpleCoreLib-1.18.2-4.3.1.3
SimpleOres2-1.18.2-4.1.2.5
Fusion-1.18.2-4.1.0.2
OnlySilver-1.18.2-4.1.0.1

I think it has something to do with the new way you handle bow properties via SimpleCore? I'm not a mod dev so i'm only guessing here though.

**Comment by Sinhika** [comment]
I broke it trying to fix something else. I have unbroken it, but CurseForge appears to be sitting on the new version of SimpleCoreLib that fixes it, so you can't use it with the new, fixed versions of SimpleOres2, Fusion, and OnlySilver. They are also sitting on some of them, too. Trust me, it is fixed, and you'll see it someday.
