### ISSUE TITLE
Exception in loading

### ISSUE THREAD

**Issue by fpinkela** [Sinhika/SimpleCore#15]
[12:51:00] [main/FATAL] [ne.mi.fm.ModLoader/CORE]: Error during pre-loading phase
net.minecraftforge.fml.ModLoadingException: Mod ?esimpleores?r requires ?6simplecorelib?r ?o1.18.2-4.3.1.4 or above, and below 1.18.2-4.4.0.0?r
?7Currently, ?6simplecorelib?r?7 is ?o1.18.2-4.3.1.3

I don't see the version it's asking for.
Thanks.

**Comment by Sinhika** [comment]
The version it's asking for has been held up by CurseForge's review process. I had no idea they would sit on the library and permit all the dependent mods to go through...

**Comment by Sinhika** [comment]
I uploaded a new version of [SimpleOres2-1.18.2-4.1.2.7.jar](https://www.curseforge.com/minecraft/mc-mods/simpleores/files/3800529) that rolls back the required version of SimpleCoreLib to what is currently available. Hopefully CurseForge processes it in a timely fashion and doesn't put it aside for review. Oh crap they did.

**Comment by fpinkela** [comment]
Thanks for the quick response. No biggie still WIP anyway.

**Comment by Sinhika** [comment]
CurseForge has released the missing version, finally. You can download it now.
