### ISSUE TITLE
[1.10.2] EnderIO JEI Plugin not loading

### ISSUE THREAD

**Issue by exp111** [Sinhika/SimpleCore#3]
So I already told the EnderIO Dev about this problem and he redirected me to you (to alexndr but as you are the maintainer right now): https://github.com/SleepyTrousers/EnderIO/issues/3540

JEI can't load the EnderIO Plugin probably because of your API.

Here are the logs again:
Full log:
http://puu.sh/q88p3/822afc37e7.log

The plugin related part:
http://pastebin.com/nh4w2bea

Hope you can help me out here

**Comment by Sinhika** [comment]
I think I see a possible problem; I'll try fixing that, but I may need you to test the fix.

**Comment by Sinhika** [comment]
I have uploaded an alpha test version (
simplecore-1.10.2-1.3.6.40.jar ) to CurseForge. As soon as it is approved, please test to see if it fixes your problem.

http://minecraft.curseforge.com/projects/simplecore-api/files/2317449

If that doesn't fix the problem, it'll have to wait until the weekend when I have time for more extensive debugging.

**Comment by exp111** [comment]
It works for me. So no problems anymore...

Thanks for your quick help^^
