### ISSUE TITLE
Crash whilst playing minecraft

### ISSUE THREAD

**Issue by DatrixTHLK** [Sinhika/SimpleCore#8]
Hello, 
This crash log output this error while playing in game single-player
https://gist.github.com/DatrixTHLK/094734c70a971856ad58c5ce4792f869
Minecraft: 1.10.2
Forge: 12.18.2.2125
SimpleCore: 1.3.13.0

If you know of this already then you may close the issue and I'll wait for a fix
I'll make sure to post this at netherrocks issue page just incase

**Comment by Sinhika** [comment]
I think this is the same bug as #7.  I will take a look at it. Just out of curiousity, why are you wearing a strawberry?

**Comment by DatrixTHLK** [comment]
Hi Sinhika, thanks for the response.

@Sinhika I really have no clue how I got a strawberry in that armor slot. 

Edit: In my foot armor slot to be exact. My guess is that I had 1 slot left in my inventory for an item, since I had magnet mode on (FEI), I ended up getting two items and the strawberry went into the armor slot because it went into my inventory at the same time as another item did. That hasn't happened before though. 

My issue with this is that the strawberry was never an armor piece to begin with. I wonder why it would go into the armor slot?

**Comment by Sinhika** [comment]
Yep, it was the same bug. Simple fix; I just uploaded SimpleCore-1.10.2-1.3.14.0.jar. 

ETA: Apparently some things cause the normal slot checks to be bypassed?  I have been watching ForgeCraft S10 with Direwolf20, and one of the buggy beta mods would load all kinds of weird stuff into DW20's armor inventory when he shift-clicked one of the machines...

**Comment by DatrixTHLK** [comment]
@Sinhika Thanks for the fix.
